version: '3.4'

services:
  espresso:
    image: espresso
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 9701:9701
